// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// dotenv loads DATABASE_URL from a local .env during development. In Docker the
// value is injected via compose env, and dotenv may not be installed, so the
// import is best-effort — a missing module must not abort `prisma db push`.
try {
  await import("dotenv/config");
} catch {
  // dotenv not installed (e.g. production/Docker) — env is already populated.
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
